
import type { NavItem, ToolbarSection, ToolbarSectionKey } from '@/contexts/navigation-context';
import {
  Home as HomeIcon,
  Mail,
  Contact as ContactIcon,
  ListChecks,
  CalendarDays,
  Briefcase,
  Workflow,
  KanbanSquare,
  FileText,
  BarChart2,
  BarChart3,
  Users,
  TrendingUp,
  Repeat,
  ShieldAlert,
  PieChart,
  Shapes,
  FlaskConical,
  LayoutGrid,
  Edit3,
  Send,
  Shield,
  Settings,
  UserCircle2,
  Landmark,
  Receipt,
  Percent,
  Package,
  ArrowRightLeft,
  Truck,
  StickyNote,
  CandlestickChart,
} from "lucide-react";

export const toolbarSections: ToolbarSection[] = [
    { id: 'CRM', title: 'CRM' },
    { id: 'Analytics', title: 'Analytics' },
    { id: 'Outreach', title: 'Outreach' },
    { id: 'Portal', title: 'Portal' },
    { id: 'Trading', title: 'Trading' },
    { id: 'Resources', title: 'Resources' },
    { id: 'Jira', title: 'Jira' },
    { id: 'Matrix Pro', title: 'Matrix Pro' },
];

export const navigationData: Record<ToolbarSectionKey, NavItem[]> = {
  'CRM': [
    { name: 'Home', icon: HomeIcon, href: '/client-portal/home' },
    { name: 'Email', icon: Mail, href: '/client-portal/email' },
    { name: 'Contacts', icon: ContactIcon, href: '/client-portal/contacts' },
    { name: 'Tasks', icon: ListChecks, href: '/client-portal/tasks' },
    { name: 'Workflows', icon: Workflow, href: '/client-portal/workflows'},
    { name: 'Calendar', icon: CalendarDays, href: '/client-portal/calendar' },
    { name: 'Opportunities', icon: Briefcase, href: '/client-portal/opportunities' },
    { name: 'Projects', icon: KanbanSquare, href: '/client-portal/projects'},
    { name: 'Files', icon: FileText, href: '/client-portal/files'},
    { name: 'Reports', icon: BarChart2, href: '/client-portal/reports' },
  ],
  'Analytics': [
    { name: 'Asset Analytics', icon: BarChart3, href: '/asset-analytics' },
    { name: 'Client Analytics', icon: Users, href: '/client-analytics' },
    { name: 'Financial Analytics', icon: TrendingUp, href: '/financial-analytics' },
    { name: 'Conversion Analytics', icon: Repeat, href: '/conversion-analytics' },
    { name: 'Compliance Matrix', icon: ShieldAlert, href: '/compliance-matrix'},
    { name: 'Portfolio Matrix', icon: PieChart, href: '/portfolio-matrix' },
    { name: 'Model Matrix', icon: Shapes, href: '/model-matrix' },
    { name: 'Contribution Matrix', icon: TrendingUp, href: '/contribution-matrix' },
    { name: 'Project X', icon: FlaskConical, href: '/project-x' },
    { name: 'Resource Matrix', icon: LayoutGrid, href: '/resource-matrix' },
  ],
  'Outreach': [
    { name: 'Inbox', icon: Mail, href: '/outreach/inbox' },
    { name: 'Compose', icon: Edit3, href: '/outreach/compose' },
    { name: 'Campaigns', icon: Send, href: '/outreach/campaigns' },
    { name: 'Templates', icon: FileText, href: '/outreach/templates' },
    { name: 'Engagement', icon: BarChart2, href: '/outreach/engagement' },
    { name: 'Compliance', icon: Shield, href: '/outreach/compliance' },
    { name: 'Settings', icon: Settings, href: '/outreach/settings' },
  ],
  'Portal': [
    { name: 'Overview', icon: LayoutGrid, href: '/portal/overview' },
    { name: 'Profile', icon: UserCircle2, href: '/portal/profile' },
    { name: 'Accounts', icon: Landmark, href: '/portal/accounts' },
    { name: 'Cost Basis', icon: Receipt, href: '/portal/cost-basis' },
    { name: 'Margin', icon: Percent, href: '/portal/margin' },
    { name: 'Positions', icon: Package, href: '/portal/positions' },
    { name: 'Transactions', icon: ArrowRightLeft, href: '/portal/transactions' },
    { name: 'Asset Movement', icon: Truck, href: '/portal/asset-movement' },
    { name: 'Documents', icon: FileText, href: '/portal/documents' },
    { name: 'Notes', icon: StickyNote, href: '/portal/notes' },
    { name: 'Communications', icon: Mail, href: '/portal/communications' },
    { name: 'Tasks', icon: ListChecks, href: '/portal/tasks' },
    { name: 'Settings', icon: Settings, href: '/portal/settings' },
  ],
  'Trading': [
    { name: 'Trading Center', icon: CandlestickChart, href: '/trading' }
  ],
  'Resources': [],
  'Jira': [],
  'Matrix Pro': [],
};
